export const SET_JOBS_FOLDER = 'SET_JOBS_FOLDER';

export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_ERROR = 'FETCH_JOBS_ERROR';

export const JOBS_FILTER_SET_TYPE = 'JOBS_FILTER_SET_TYPE';
export const JOBS_FILTER_SET_USERS = 'JOBS_FILTER_SET_USERS';
export const JOBS_FILTER_SET_DATE_RANGE = 'JOBS_FILTER_SET_DATE_RANGE';
